apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-config
data:
  REDIS_URL:     redis://redis-service:6379
  INFLUX_URL:    http://influxdb-service:8086
  INFLUX_ORG:    weather_org
  INFLUX_BUCKET: weather_bucket
